// Recreate the local database (shim + migrations + seed), copy demo images
// into the local storage folder and write .env.local for Vite.
//   pnpm local:setup
import { randomBytes } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { generateVapidKeys } from '../lib/vapid.ts';
import pg from 'pg';
import { buildSeed } from '../tenant/seed-gen.ts';
import { listTenantSlugs, validateTenant } from '../tenant/load.ts';
import { ADMIN_DB_URL, GATEWAY_URL, LOCAL_DB_URL, MEDIA_DIR, PUBLISHABLE_KEY, ROOT, SECRET_KEY } from './env.ts';

const dbName = LOCAL_DB_URL.split('/').pop()!;
const admin = new pg.Client({ connectionString: ADMIN_DB_URL });
await admin.connect();
await admin.query(`drop database if exists ${dbName} with (force)`);
await admin.query(`create database ${dbName}`);
await admin.end();

const db = new pg.Client({ connectionString: LOCAL_DB_URL });
await db.connect();
await db.query(readFileSync(path.join(ROOT, 'supabase/local/shim.sql'), 'utf8'));
const { readdirSync } = await import('node:fs');
for (const f of readdirSync(path.join(ROOT, 'supabase/migrations')).filter((x) => x.endsWith('.sql')).sort()) {
  await db.query(readFileSync(path.join(ROOT, 'supabase/migrations', f), 'utf8'));
}
const seed = await buildSeed();
writeFileSync(path.join(ROOT, 'supabase/seed.sql'), seed);
await db.query(seed);

// demo media -> local storage (what tenant:publish uploads on a real project)
rmSync(MEDIA_DIR, { recursive: true, force: true });
for (const slug of listTenantSlugs()) {
  const v = await validateTenant(slug);
  const { rows } = await db.query(`select id from public.tenants where slug = $1`, [slug]);
  const target = path.join(MEDIA_DIR, 'tenant-media', rows[0].id, 'config');
  mkdirSync(target, { recursive: true });
  const files = [v.tenant!.config.images.logo, v.tenant!.config.images.hero, ...v.tenant!.config.gallery.map((g) => g.image)];
  for (const f of files) {
    const src = path.join(ROOT, 'tenants', slug, 'images', f);
    if (existsSync(src)) cpSync(src, path.join(target, path.basename(f)));
  }
  await db.query(`insert into storage.objects(bucket_id, name) select 'tenant-media', $1 || '/config/' || x from unnest($2::text[]) x on conflict do nothing`,
    [rows[0].id, files.map((f) => path.basename(f))]);
}
await db.end();

// Keep local VAPID keys and cron secret between runs so browser subscriptions stay valid.
const prev = existsSync(path.join(ROOT, '.env.local')) ? readFileSync(path.join(ROOT, '.env.local'), 'utf8') : '';
const prevVar = (k: string) => new RegExp(`^${k}=(.+)$`, 'm').exec(prev)?.[1];
let vapidPublic = prevVar('VITE_VAPID_PUBLIC_KEY');
let vapidPrivate = prevVar('VAPID_PRIVATE_KEY');
if (!vapidPublic || !vapidPrivate) ({ publicKey: vapidPublic, privateKey: vapidPrivate } = await generateVapidKeys());
const cronSecret = prevVar('NOTIFY_CRON_SECRET') ?? randomBytes(24).toString('hex');

const env = [
  '# Generated by pnpm local:setup — local gateway, not a real Supabase project.',
  `VITE_SUPABASE_URL=${GATEWAY_URL}`,
  `VITE_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}`,
  `VITE_VAPID_PUBLIC_KEY=${vapidPublic}`,
  '',
  '# server-side only (scripts), never exposed to the browser',
  `SUPABASE_URL=${GATEWAY_URL}`,
  `SUPABASE_SECRET_KEY=${SECRET_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${SECRET_KEY}`, // what the Edge runtime provides to functions
  `VAPID_PUBLIC_KEY=${vapidPublic}`,
  `VAPID_PRIVATE_KEY=${vapidPrivate}`,
  'VAPID_SUBJECT=mailto:local@example.invalid',
  `NOTIFY_CRON_SECRET=${cronSecret}`,
  '',
].join('\n');
writeFileSync(path.join(ROOT, '.env.local'), env);
// Local production builds (pnpm build) must also talk to the emulator, not to
// the real project in the committed .env.production.
writeFileSync(
  path.join(ROOT, '.env.production.local'),
  ['# Generated by pnpm local:setup: overrides .env.production for local builds.', `VITE_SUPABASE_URL=${GATEWAY_URL}`, `VITE_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}`, `VITE_VAPID_PUBLIC_KEY=${vapidPublic}`, ''].join('\n'),
);
console.log(`local database ${dbName} ready; .env.local written; media in ${path.relative(ROOT, MEDIA_DIR)}`);
