// Build supabase/seed.sql from tenants/*/business.json:
//  * publishes every demo studio through pipeline_publish_tenant (preview)
//  * adds the flagged demo bookings (pipeline_seed_demo)
//  * creates one demo owner per studio for local/preview use
// seed.sql runs on `supabase db reset` and on our local database; it is not
// applied to production by `supabase db push`.
//   pnpm db:seed
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { listTenantSlugs, ROOT, validateTenant } from './load.ts';

export const DEMO_OWNER_PASSWORD = 'demo-owner-2026';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

export async function buildSeed() {
  const parts: string[] = [
    '-- GENERATED by scripts/tenant/seed-gen.ts from tenants/*/business.json. Do not edit by hand.',
    '-- Demo studios (status preview), demo-flagged bookings and demo owner accounts.',
    `-- Demo owner password for every studio: ${DEMO_OWNER_PASSWORD}`,
    '',
  ];
  for (const slug of listTenantSlugs()) {
    const v = await validateTenant(slug);
    if (!v.ok || !v.tenant) throw new Error(`${slug}: ${v.errors.join('; ')}`);
    const cfg = { ...v.tenant.config, config_hash: v.tenant.hash };
    delete (cfg as Record<string, unknown>).$schema;
    parts.push(`-- ${slug}`);
    parts.push(`select public.pipeline_publish_tenant(${q(JSON.stringify(cfg))}::jsonb);`);
    parts.push(`select public.pipeline_seed_demo(${q(slug)});`);
    const email = v.tenant.config.owner?.email;
    if (email) {
      parts.push(`with u as (
  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
    confirmation_token, recovery_token, email_change_token_new, email_change)
  values ('00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', ${q(email)},
    extensions.crypt(${q(DEMO_OWNER_PASSWORD)}, extensions.gen_salt('bf')), now(),
    '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '')
  on conflict (email) do update set updated_at = now()
  returning id, email
), i as (
  insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  select u.id::text, u.id, jsonb_build_object('sub', u.id::text, 'email', u.email, 'email_verified', true), 'email', now(), now(), now()
  from u
  on conflict (provider_id, provider) do nothing
)
select public.pipeline_add_member(${q(slug)}, (select id from u), 'owner');`);
    }
    parts.push('');
  }
  return parts.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const sql = await buildSeed();
  const out = path.join(ROOT, 'supabase/seed.sql');
  writeFileSync(out, sql);
  console.log(`wrote ${path.relative(ROOT, out)}`);
}
